"""Curated Genshin Impact static data for material/boss queries.

Data files in this directory are generated by tools/generate_data.py
from Dimbreath API and checked into git for zero-runtime-dependency loading.
"""
